os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - swift build
  - swift build -c release
  - swift test
deploy:
    provider: heroku
    api_key:
        secure: 481b1f57-9036-4b49-ae28-b799ddc92b87
    app: trello-copy-backend
    on:
        branch: master