os: osx
language: swift
osx_image: xcode11
before_script:
- gem install xcpretty
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme backend-Package clean build test | xcpretty
deploy:
    provider: heroku
    api_key:
        secure: 55feebef-2dd0-4711-b02a-589002626d61
    app: paw-trello-backend
    on:
        branch: master