os: osx
language: swift
osx_image: xcode11
addons:
  homebrew:
    packages:
    - libressl
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
    - .build
before_script:
- gem install xcpretty
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme backend-Package clean build test | xcpretty
deploy:
    provider: heroku
    api_key:
        secure: 55feebef-2dd0-4711-b02a-589002626d61
    app: paw-trello-backend
    on:
        branch: master